export interface TeaProduct {
  id: number;
  name: string;
  category: 'Black Tea' | 'Green Tea' | 'Herbal Tea' | 'Special Tea';
  price: number;
  image: string;
  flavornote: string;
  description: string;
}

export const teaProducts: TeaProduct[] = [
  // Black Tea
  {
    id: 1,
    name: 'Cinnamon Black Tea',
    category: 'Black Tea',
    price: 950,
    image: '/images/blackcinnamon.jpg',
    flavornote: 'Warm, spicy and aromatic',
    description: 'A bold black tea infused with smooth cinnamon notes for a warming and comforting cup.',
  },
  {
    id: 2,
    name: 'Black Earl Grey Tea',
    category: 'Black Tea',
    price: 1100,
    image: '/images/blackearlgrey.jpg',
    flavornote: 'Citrusy bergamot aroma',
    description: 'Classic Earl Grey blended with rich black tea and the refreshing essence of bergamot.',
  },
  {
    id: 3,
    name: 'Mint Black Tea',
    category: 'Black Tea',
    price: 900,
    image: '/images/blacklemonlift.jpg',
    flavornote: 'Cool minty freshness',
    description: 'Smooth black tea paired with a refreshing mint twist for an energizing taste.',
  },
  {
    id: 4,
    name: 'Lemon Lift Black Tea',
    category: 'Black Tea',
    price: 950,
    image: '/images/blackmint.jpg',
    flavornote: 'Light lemon zest aroma',
    description: 'A vibrant black tea blend lifted with bright lemon for a refreshing and clean finish.',
  },
  {
    id: 5,
    name: 'Vanilla Black Tea',
    category: 'Black Tea',
    price: 1200,
    image: '/images/blacksaltedcaramel.jpg',
    flavornote: 'Smooth and creamy vanilla',
    description: 'Silky vanilla blended with strong black tea to create a rich, comforting flavor.',
  },
  {
    id: 6,
    name: 'Salted Caramel Black Tea',
    category: 'Black Tea',
    price: 1250,
    image: '/images/blackvanila.jpg',
    flavornote: 'Sweet caramel with a hint of salt',
    description: 'A deliciously sweet caramel infusion balanced with a touch of salt and bold black tea.',
  },

  // Green Tea
  {
    id: 7,
    name: 'Classic Green Tea',
    category: 'Green Tea',
    price: 850,
    image: '/images/greenclassic.jpg',
    flavornote: 'Earthy and naturally fresh',
    description: 'Pure green tea with a clean and calming flavor, perfect for daily wellness.',
  },
  {
    id: 8,
    name: 'Ginger Green Tea',
    category: 'Green Tea',
    price: 900,
    image: '/images/greenginger.jpg',
    flavornote: 'Warm ginger spice',
    description: 'Green tea blended with invigorating ginger for a soothing and energizing drink.',
  },
  {
    id: 9,
    name: 'Lemongrass Green Tea',
    category: 'Green Tea',
    price: 950,
    image: '/images/greenlemongrass.jpg',
    flavornote: 'Fresh citrusy aroma',
    description: 'A refreshing mix of green tea and lemongrass with a bright, calming taste.',
  },
  {
    id: 10,
    name: 'Matcha Green Tea',
    category: 'Green Tea',
    price: 1650,
    image: '/images/greenmacha.jpg',
    flavornote: 'Smooth and earthy',
    description: 'Finely ground matcha powder delivering a rich, energizing, antioxidant-packed cup.',
  },
  {
    id: 11,
    name: 'Peach Green Tea',
    category: 'Green Tea',
    price: 1000,
    image: '/images/greenpeach.jpg',
    flavornote: 'Sweet fruity peach',
    description: 'A delightful green tea infused with juicy peach flavor for a refreshing sip.',
  },
  {
    id: 12,
    name: 'Peppermint Green Tea',
    category: 'Green Tea',
    price: 900,
    image: '/images/greenpeppermint.jpg',
    flavornote: 'Cool peppermint notes',
    description: 'Green tea blended with pure peppermint for a crisp, soothing, and uplifting taste.',
  },

  // Herbal Tea
  {
    id: 13,
    name: 'Camomile Herbal Tea',
    category: 'Herbal Tea',
    price: 1100,
    image: '/images/camomile1.jpg',
    flavornote: 'Soft floral sweetness',
    description: 'A calming herbal infusion made from chamomile flowers, ideal for relaxation.',
  },
  {
    id: 14,
    name: 'Fennel Herbal Tea',
    category: 'Herbal Tea',
    price: 1000,
    image: '/images/Fennel.jpg',
    flavornote: 'Mild sweet anise',
    description: 'A soothing fennel tea with gentle sweetness, perfect for digestion and calmness.',
  },
  {
    id: 15,
    name: 'Lemon Ginger Herbal Tea',
    category: 'Herbal Tea',
    price: 1150,
    image: '/images/lemonginger.jpg',
    flavornote: 'Zesty lemon and warm ginger',
    description: 'A revitalizing herbal blend combining ginger spice and fresh lemon zest.',
  },
  {
    id: 16,
    name: 'Nettle Leaf Herbal Tea',
    category: 'Herbal Tea',
    price: 1250,
    image: '/images/NettleLeaf.jpg',
    flavornote: 'Mild earthy greens',
    description: 'A nutrient-rich herbal tea made from nettle leaves, known for its natural cleansing properties.',
  },
  {
    id: 17,
    name: 'Peppermint Herbal Tea',
    category: 'Herbal Tea',
    price: 900,
    image: '/images/peppermint.jpg',
    flavornote: 'Refreshing cool mint',
    description: 'Pure peppermint leaves offering a cooling, soothing, and aromatic herbal drink.',
  },
  {
    id: 18,
    name: 'RoseHip Hibiscus Herbal Tea',
    category: 'Herbal Tea',
    price: 1350,
    image: '/images/RoseHipHibiscus.jpg',
    flavornote: 'Tangy floral blend',
    description: 'A vibrant mix of rosehip and hibiscus, delivering a tart, fruity and refreshing flavor.',
  },

  // Special Tea
  {
    id: 19,
    name: 'Breathe Easy Tea',
    category: 'Special Tea',
    price: 1500,
    image: '/images/spbreathe.jpg',
    flavornote: 'Cooling herbal freshness',
    description: 'A soothing blend crafted to refresh your senses and support easy breathing.',
  },
  {
    id: 20,
    name: 'Cold Care Tea',
    category: 'Special Tea',
    price: 1550,
    image: '/images/spcold.jpg',
    flavornote: 'Warm herbal comfort',
    description: 'A comforting herbal tea formulated to warm your body and support recovery during cold weather.',
  },
  {
    id: 21,
    name: 'Healthy Cycle Tea',
    category: 'Special Tea',
    price: 1600,
    image: '/images/sphelthy.jpg',
    flavornote: 'Soft floral herbs',
    description: 'A gentle herbal blend designed to support balance and natural wellness.',
  },
  {
    id: 22,
    name: 'Special Night Tea',
    category: 'Special Tea',
    price: 1500,
    image: '/images/spnight.jpg',
    flavornote: 'Relaxing floral aroma',
    description: 'A calming nighttime blend that helps you unwind and prepare for restful sleep.',
  },
  {
    id: 23,
    name: 'Throat Coat Tea',
    category: 'Special Tea',
    price: 1550,
    image: '/images/spthroat.jpg',
    flavornote: 'Smooth herbal sweetness',
    description: 'A soothing herbal infusion crafted to comfort your throat and provide gentle relief.',
  },
  {
    id: 24,
    name: 'Stress Ease Tea',
    category: 'Special Tea',
    price: 1600,
    image: '/images/spstress.jpg',
    flavornote: 'Light calming herbs',
    description: 'A stress-relieving herbal tea created to relax your mind and restore balance.',
  },
];
